// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.androidapp.mp3App;

public class _FunctionPrxI extends com.zeroc.Ice._ObjectPrxI implements FunctionPrx
{
    public static final long serialVersionUID = 0L;
}
