// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.0
//
// <auto-generated>
//
// Generated from file `server.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.androidapp.mp3App;

public class Song implements java.lang.Cloneable,
                             java.io.Serializable
{
    public String name;

    public String artist;

    public String genre;

    public String length;

    public String path;

    public Song()
    {
        this.name = "";
        this.artist = "";
        this.genre = "";
        this.length = "";
        this.path = "";
    }

    public Song(String name, String artist, String genre, String length, String path)
    {
        this.name = name;
        this.artist = artist;
        this.genre = genre;
        this.length = length;
        this.path = path;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Song r = null;
        if(rhs instanceof Song)
        {
            r = (Song)rhs;
        }

        if(r != null)
        {
            if(this.name != r.name)
            {
                if(this.name == null || r.name == null || !this.name.equals(r.name))
                {
                    return false;
                }
            }
            if(this.artist != r.artist)
            {
                if(this.artist == null || r.artist == null || !this.artist.equals(r.artist))
                {
                    return false;
                }
            }
            if(this.genre != r.genre)
            {
                if(this.genre == null || r.genre == null || !this.genre.equals(r.genre))
                {
                    return false;
                }
            }
            if(this.length != r.length)
            {
                if(this.length == null || r.length == null || !this.length.equals(r.length))
                {
                    return false;
                }
            }
            if(this.path != r.path)
            {
                if(this.path == null || r.path == null || !this.path.equals(r.path))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::mp3App::Song");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, name);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, artist);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, genre);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, length);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, path);
        return h_;
    }

    public Song clone()
    {
        Song c = null;
        try
        {
            c = (Song)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeString(this.name);
        ostr.writeString(this.artist);
        ostr.writeString(this.genre);
        ostr.writeString(this.length);
        ostr.writeString(this.path);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.name = istr.readString();
        this.artist = istr.readString();
        this.genre = istr.readString();
        this.length = istr.readString();
        this.path = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Song v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Song ice_read(com.zeroc.Ice.InputStream istr)
    {
        Song v = new Song();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Song> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Song v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Song> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Song.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Song _nullMarshalValue = new Song();

    public static final long serialVersionUID = -773765102L;
}
